### ISSUE TITLE
import errors in bundled version

### ISSUE THREAD

**Issue by pazz** [lorenzschmid/jekyll-congress#12]
Hi!

I've just tried out your updated gem-based version and am running into some import problems.
I post these below in the hope this helps you. I'm not a ruby programmer so cannot really debug this easily.

I'm on debian testing and have the following versions:

```terminal
[~/conference] ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
[~/conference] bundle -v
Bundler version 2.1.4
```

I have followed your README to the dot. For the config I copied the example config file into `myblog/_config.yml`. 

```terminal
[~/conference] ll
total 8.0K
drwxr-xr-x 16 pazz pazz 4.0K May  8 14:30 jekyll-conference
drwxr-xr-x 12 pazz pazz 4.0K May  8 14:36 myblog
[~/conference] cd myblog 
[~/conference/myblog] ls
404.html        _config.yml      _data    Gemfile.lock  _location  _posts  _speakers  _talks
about.markdown  _config.yml.old  Gemfile  index.md      location   _site   speakers   talks
```

Executing `bundle` [looks good to me](https://gist.github.com/pazz/d57a4ac9851d3c970d78a33360ccc6b3).

Now `bundle exec jekyll serve` give this: (see [here](https://gist.github.com/pazz/bba308f192cfe9a20bc06585fe39b948) for full output).

```
       Jekyll Feed: Generating feed for posts
     Build Warning: Layout 'post' requested in _posts/2020-05-08-welcome-to-jekyll.markdown does not exist.
     Build Warning: Layout 'talks' requested in _talks/talk1.md does not exist.
     Build Warning: Layout 'talks' requested in _talks/talk2.md does not exist.
     Build Warning: Layout 'talks' requested in _talks/talk3.md does not exist.
     Build Warning: Layout 'talks' requested in _talks/talk4.md does not exist.
     Build Warning: Layout 'speakers' requested in _speakers/person-a.md does not exist.
     Build Warning: Layout 'speakers' requested in _speakers/person-b.md does not exist.
     Build Warning: Layout 'speakers' requested in _speakers/person-c.md does not exist.
     Build Warning: Layout 'location' requested in _location/room-a.md does not exist.
     Build Warning: Layout 'location' requested in _location/room-b.md does not exist.
     Build Warning: Layout 'location' requested in _location/room-c.md does not exist.
     Build Warning: Layout 'default' requested in 404.html does not exist.
     Build Warning: Layout 'page' requested in about.markdown does not exist.
     Build Warning: Layout 'overview_talks' requested in talks/index.md does not exist.
     Build Warning: Layout 'location' requested in location/index.md does not exist.
     Build Warning: Layout 'overview_speakers' requested in speakers/index.md does not exist.
     Build Warning: Layout 'main' requested in index.md does not exist.
                    done in 0.209 seconds.
 Auto-regeneration: enabled for '/home/pazz/repo/orga/BCTCS2021/new/myblog'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```
Now of course the website does not look as expected in the browser.
I should say that the problem is not caused by me using a symlink `~/conference` to a longer path. This is just to make the presentation here shorter.

An emmediate attempt to "fix" this by copying the folder `_layouts` fro myou repo to the project directory did not solve my problem (it resulted in other unmet dependencies used in these layouts).

I suspect something's off with your gem thingie?

**Comment by pazz** [comment]
I forgot to mention: This uses your code from the master branch, 5a11c28508a1621facff9ee132ea706d03bfb708.

```terminal
bundle info jekyll-theme-conference
  * jekyll-theme-conference (2.0.0)
	Summary: Jekyll template for a conference website containing program, speaker, talks and room overview.
	Homepage: https://github.com/DigitaleGesellschaft/jekyll-conference/
	Path: /home/pazz/repo/orga/BCTCS2021/new/jekyll-conference
```

**Comment by pazz** [comment]
I (believe I) have re-installed jekyll and bundler using `gem install` again, and followed [these docs on gem-based themes](https://jekyllrb.com/docs/themes/) (to create a new project, and change the theme, but not yet copied over stuff from your repo. This should not be necessary ideally anyways).

It seems there is some import error in the main css file:
https://gist.github.com/pazz/71249f00eccf5a1b4e492bd6c8c41f6e

It is entirely possible that this is an unrelated new issue, in which case apologies for mixing this in here. I suspect that we have different versions of jekyll and they have made them incompatible recently.

```
bundle exec jekyll --version 
jekyll 4.0.1
```

**Comment by lorenzschmid** [comment]
Thanks a lot for your feedback and sorry for your troubles. I did a major rebasing when moving the entire theme to the Gem based approach - apparently with some hickups. I intend to publish the Gem to RubyGems once everything runs smooth (latest in a few weeks) until then you might find one or the other thing broken. Sorry for that.

About your issues: I simplified the setup process described in the README file in ad45b57. By simply coping the default content from this repo as a start everything should now work. Please try again and let me know if there are any issues (and feel free to reopen this issue if needed).

**Comment by pazz** [comment]
No worries, I appreciate your responsiveness and pushing this forward.

I've now checked again with  the updated version from the master branch:
The missing layout errors are indeed gone now, but I still get [this import error](https://gist.github.com/pazz/71249f00eccf5a1b4e492bd6c8c41f6e) upon `bundle exec jekyll serve`. This uses your default config and I've just moved content as suggested in the README file. Let me know when I should try again.

**Comment by lorenzschmid** [comment]
Thanks for posting your newly discovered error: My `.gitignore` file was improperly configured and thus not all sources from a dependency were committed - obviously on my machine this issue never surfaced as the data existed. I fixed it and just tested it by cloning this repo and creating a new test website: Should finally work! Thanks again!

**Comment by pazz** [comment]
Yes, I  can confirm it works as expected now. Cheers!

(by the way: in the README, you may want to say that one should remove the existing `_posts` directory and `*markdown` files generated by `jekyll new`, and merge the "Install" and "setup" sections to make things simpler for prospective users).
