### ISSUE TITLE
Location: Leaflet integration not working as expected 

### ISSUE THREAD

**Issue by pazz** [lorenzschmid/jekyll-congress#9]
Apologies for the newbie question (I'm not really a web developer):

The leaflet integration seems broken. I see only a gray background map instead of an openstreetmap overlay (see below). This is using pretty much an unchanged version from your master branch.

Any idea how to debug this? Am I overlooking some user token for leaflet or so that I need to integrate?
Thanks again for the awesome template and any pointers on this issue.

![map](https://user-images.githubusercontent.com/628455/79070847-25f3d500-7cd0-11ea-9014-86b699ed57b4.png)

**Comment by lorenzschmid** [comment]
No errors on your side: The server providing the map tiles seems to have crashed over Easter and thus is currently not responding (as stated on the [OpenStreetMap forum](https://help.openstreetmap.org/questions/68610/hydda-map-tiles-not-working/74085)).

You can easily switch the tile provider by yourself and replace the current one: On [line 7 in `map.js`](https://github.com/DigitaleGesellschaft/jekyll-conference/blob/master/assets/js/map.js#L7) simply replace the old provider `Hydda.Full` with a new, working one, e.g. `Esri.WorldTopoMap` (or any [other](https://leaflet-extras.github.io/leaflet-providers/preview/)).

**Comment by pazz** [comment]
Awesome, thanks!
